CREATE DATABASE IF NOT EXISTS radiko_manager CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE USER IF NOT EXISTS 'user'@'%' IDENTIFIED BY $RADIKO_MANAGER_DATABASE_PASSWORD;
GRANT ALL PRIVILEGES ON radiko_manager.* TO 'user'@'%';

FLUSH PRIVILEGES;
